name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install --repo-update
      working-directory: Example
    - name: Run tests
      run: |
        fastlane scan
      working-directory: Example
