name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  xcodebuild-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install --repo-update
      working-directory: Example
    - name: Run tests
      run: |
        xcrun xcodebuild test -workspace WalletConnect.xcworkspace -scheme WalletConnect-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
      working-directory: Example
